# Generated by Django 4.0 on 2022-04-15 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='niveau',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(22), django.core.validators.MaxValueValidator(39)]),
        ),
    ]
